### ISSUE TITLE
[help] Couldn't find db entry for file error 

### ISSUE THREAD

**Issue by tao101** [h4ck-rOOt/Lynda-Decryptor#7] opened 2016-10-22 19:44 UTC
when i run Lynda-Decryptor i  get this error  Couldn't find db entry for file please can you help me 
here is what i see on cmd after i run it 

`[ARGS] Changing mode to Folder decryption!
[START] Init Decryptor...
[START] Decryptor successful initalized!

[DB] Creating db connection...
[DB] DB successfully connected and opened!

[STATUS] Couldn't find db entry for file: E:\lynda\ldc_dl_courses\1014613\114513_83218ac34c1834c26781fe4bde918ee4.lynda
[STATUS] Using the default behaviour!
[STATUS] Couldn't find db entry for file: E:\lynda\ldc_dl_courses\1014613\114514_004d3e2a4856b16f30a875347fa180b1.lynda
[STATUS] Using the default behaviour!
[STATUS] Couldn't find db entry for file: E:\lynda\ldc_dl_courses\1014613\114515_b37c2c183d5a4009e0a54324a407a534.lynda
[STATUS] Using the default behaviour!
[STATUS] Couldn't find db entry for file: E:\lynda\ldc_dl_courses\1014613\114517_59fb4daef47c4be4d7dad15c0cb33a9c.lynda
[STATUS] Using the default behaviour!
[STATUS] Couldn't find db entry for file: E:\lynda\ldc_dl_courses\1014613\114518_8a45870b2be74f6f344f8f375f7be936.lynda
[STATUS] Using the default behaviour!
[STATUS] Couldn't find db entry for file: E:\lynda\ldc_dl_courses\1014613\114519_a21b3b0bc1d31d6843a0760175cb3986.lynda
[STATUS] Using the default behaviour!
`

**Comment by h4ck-rOOt** [comment] 2016-11-06 10:36
Hello @tao101,

I think this is a duplicate of #6, so please take a look there.

Thanks for using this little program.

**Closed by h4ck-rOOt** 2016-11-06 10:36 UTC
